### ISSUE TITLE
Plot is very slow to display large array via overlay_array

### ISSUE THREAD

**Issue by nispio** [LGSInnovations/jupyter-sigplot#44] opened 2019-03-28 20:46 UTC
When I use `overlay_array` to plot a large array (e.g. 20M points) it takes a significant amount of time (i.e. over one minute) for the data to be displayed in the widget. This is basically what my notebook looks like:

`In[1]:`

    from jupyter_sigplot.sigplot import SigPlot
    import numpy as np

    x = np.arange(0, 200e3, 0.01)
    sinx = np.sin(x)
    cosx = np.cos(x)

`In[2]:`

    plot = SigPlot(sinx, cosx, xi=True, cross=True, all=True)
    plot.plot()

`In[4]:`

    # After writing sinx and cosx to Type 1000 'SF' files ...
    plot = SigPlot("sinx.tmp", "cosx.tmp", xi=True, cross=True, all=True)
    plot.plot()

When I evaluate the second cell, a blank plot is displayed right away, but the data takes over a minute to show up, and there is no indication that any background work is taking place.

When I evaluate the fourth cell, the full plot is displayed almost instantly, including the data.

**Comment by nispio** [comment] 2019-03-29 16:55
I tested this at home, and it worked significantly faster.  A 200K-element array only took a few seconds to plot.  The system that is running slow is actually an OpenStack VM, but it has 8 cores and 15 GB of RAM, both of which are greater than my home workstation.  The OpenStack instance is running a hardened CentOS7, and my home machine is running Ubuntu 18.04.

Any suggestions on what and how to test for bottlenecks?

**Comment by sterre** [comment] 2019-03-29 17:19
I know that Websockets in general are capable of transmitting binary data. If I get time, I'd like to look into whether the Jupyter Comm abstraction has somewhere we could hook into for binary transport instead of JSON.

**Comment by maihde** [comment] 2019-03-29 21:40
@nispio if you can, open up the Chrome Developer tools and make a HAR file capture of the slow plot.

(https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366)

Then send me the HAR file privately or attached to this commit.  This will help us understand where the slow down is coming from.

**Comment by mrecachinas** [comment] 2019-03-30 09:46
Also @nispio what browser and browser version are you using?

**Comment by maihde** [comment] 2019-03-30 14:17
@nispio I'm able to reproduce this behavior as well.  In my case the slow down is definitely on the Python side and is part of the Jupyter COMM subsystem which uses Traitlets to synchronize the arrays from the backend engine to the front end.

From what I can tell so far, it's either: (a) the serialization of the array to JSON or (b) the Traitlet comparison of objects.

My environment is:

- Ubuntu Bionic (running in a VirtualBox VM)
- Chrome 73.0.3683.86
- Python 3

**Comment by maihde** [comment] 2019-03-30 14:33
Here is a link that shows a technique that we might be able to use to transfer binary data instead of Json (https://gist.github.com/maartenbreddels/40fa030fdb922e6d2074282ceed6b753).

**Comment by mrecachinas** [comment] 2019-03-31 12:29
There are a few options @maihde and I have been discussing, and this ties in nicely with @desean1625's comments on Slack:

## Options:
1. Pass raw binary over Jupyter COMM following the [link](https://gist.github.com/maartenbreddels/40fa030fdb922e6d2074282ceed6b753) @maihde posted above.
2. Follow a technique similar to Matplotlib. Matplotlib passes the base64 encoded PNG data of the plot to the server, and when the user selects an area to zoom into, the client (JS) sends a "resize" message to the server, which regenerates an image and sends it back to the client to display. See: [matplotlib/mpl.js#L299-L303](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/js/mpl.js#L299-L303), [matplotlib/mpl.js#L399-448](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/js/mpl.js#L399-L448), and [backend_nbagg.py](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_nbagg.py). This is also how Matplotlib is able to retain plots on close -- because the png data is kept within the notebook itself and no JS needs to be executed (tying in nicely with #26).

Right now option (1) is the most feasible and simplest, but (2) has been discussed before, and keeps coming up in similar discussions for SigPlot (cf. @desean1625's Slack comments), and clearly reaches into design decisions with SigPlot (e.g., XCMP) and the saving plots in Jupyter-SigPlot.

**Comment by sterre** [comment] 2019-04-01 16:35
One difference between Matplotlib and SigPlot is that Matplotlib actually does all the rendering on the server (kernel), whereas SigPlot, being native Javascript, can (and currently does) render on the client. 

Another is that the `%matplotlib inline` version of Matplotlib uses only a rich representation, not a widget. (`%matplotlib notebook` is different)

When we've been talking about saving rendered images with the notebook, my understanding is that we were mainly thinking the client would generate a PNG after rendering, and send that back to the server to store as a rich representation, allowing saved notebooks to be viewed with embedded figures via things like nbviewer. This is the same shape as Matplotlib, but in reverse. Just wanted to double-check that we're talking about the same thing

Just as I think Bokeh is also worth investigating in the context of saving, it may also be worth a look in the context of Comms. (I don't know/remember exactly what it does; in some cases, I'm certain that it sends a Javascript representation of the figure in question, which is definitely no better than JSON.)

Regarding the binary transport for SigPlot, I think it would have the additional virtue that SigPlot already internally traffics in ArrayBuffers (iirc), so there'd be one less translation client side, over and above the deserialization savings.

On yet another point, even if we use a binary transport, large files may take a while to arrive at the server. Some kind of progress indicator would be nice to address the OP's observation that nothing obvious occurs during loading--but note that the progress in question is in the Comm, not SigPlot proper. Imagine that SigPlot grows a way to indicate loading progress, possibly updated by XHR events in a purely Web context. Then I suggest that we have the notebook widget trigger that same mechanism, rather than also adding UI to display notebook Comm progress (presuming that we can hook into Comm progress in the first place).

And finally, on the detached header point: I bet it would not be too much work to add an "overlay href data only" capability, since we already have headermod / header-only push and the expression in the constructor is "data" plus "overrides" (header). In the notebook context, we could keep the header in a traitlet, allowing a nice Python syntax for headermod like `h.xstart = 123` (triggering an observer in the client, which would then call `SigPlot[.layer].headermod` on the client. Even without that syntax, keeping the header in memory and the data on disk could be virtuous in terms of disk access patterns.

**Comment by nispio** [comment] 2019-04-01 18:12
A quick correction/update:

I incorrectly stated before that I was plotting 200,000 points, but I later realized (to my embarrassment) that `arange(0, 200e3, 0.01)` creates 20 million points.  However, when I was testing at home, I was coding up the test notebook from scratch, and I used `r_[:200e3]*0.01` without realizing that I was not comparing apples to apples.  Plotting 20 million points at home gave performance that was similar to those described in the problem case on OpenStack.

The two takeaways from this correction:
1. The minute-plus array-plotting times were occurring for 20M points (not 200k as first stated)
2. The performance difference between my two setups was not nearly as drastic as I initially thought.

**Comment by maihde** [comment] 2019-04-01 18:28
20M points will definitely be very slow to serialize from Python to JSON
and back.  I'm glad you caught that because I overlooked the same detail
(also to my embarrassment) when attempting to reproduce your issue.

On the plus side, SigPlot can handle 20M points in either binary form or
javascript (see this fiddle  https://jsfiddle.net/kwbm1oj6/1/  ) with
minimal delay.

So it's still worth us trying to fix this in Jupyter because there is
something internal to Jupyter that is *very* slow to do the serialization.

```
#!/usr/bin/env python

import json
import random
import time

npoints = int(20e6)
data = []
for _ in range(npoints):
    data.append(random.random())
s = time.time()
dat = json.dumps(data)
e = time.time()
print "serialization took", e-s
```

Only takes 22 seconds, so something under the hood in traitlets or Jupyter
is causing a lot of extra dealy.

Regards,
~Michael

**Comment by mrecachinas** [comment] 2019-04-01 19:14
> One difference between Matplotlib and SigPlot is that Matplotlib actually does all the rendering on the server (kernel), whereas SigPlot, being native Javascript, can (and currently does) render on the client.

Yep. There are instances where we could benefit from server-side rendering or at least cleverly sending what can render on the screen (`xcmp`-style) (e.g., attempting to plot >100 MB of data).

> Another is that the %matplotlib inline version of Matplotlib uses only a rich representation, not a widget. (%matplotlib notebook is different)

That's correct. They both are technically widgets---the only difference is `%matplotlib notebook` leverages the websocket connection to send messages back to the kernel (e.g., `resize` and `pan`), so the kernel can re-render the plot and send that PNG back to the client.

> When we've been talking about saving rendered images with the notebook, my understanding is that we were mainly thinking the client would generate a PNG after rendering, and send that back to the server to store as a rich representation, allowing saved notebooks to be viewed with embedded figures via things like nbviewer. This is the same shape as Matplotlib, but in reverse. Just wanted to double-check that we're talking about the same thing.

Yep.

> Just as I think Bokeh is also worth investigating in the context of saving, it may also be worth a look in the context of Comms. (I don't know/remember exactly what it does; in some cases, I'm certain that it sends a Javascript representation of the figure in question, which is definitely no better than JSON.)

Bokeh appears to have the same issues we have. The following code both took >10 minutes to eventually crash my browser every time I ran it:

```python
In[1]: from bokeh.plotting import figure, show, output_notebook
       import numpy as np
       output_notebook()

In[2]: x = np.arange(0, 200e3, 0.01)
       sinx = np.sin(x)
       cosx = np.cos(x)

In[3]: %%timeit
       p = figure(width=300, height=300)
       p.multi_line(xs=[x, x], ys=[sinx, cosx])
       show(p)
```

> Regarding the binary transport for SigPlot, I think it would have the additional virtue that SigPlot already internally traffics in ArrayBuffers (iirc), so there'd be one less translation client side, over and above the deserialization savings.

Exactly.

> On yet another point, even if we use a binary transport, large files may take a while to arrive at the server. Some kind of progress indicator would be nice to address the OP's observation that nothing obvious occurs during loading--but note that the progress in question is in the Comm, not SigPlot proper. Imagine that SigPlot grows a way to indicate loading progress, possibly updated by XHR events in a purely Web context. Then I suggest that we have the notebook widget trigger that same mechanism, rather than also adding UI to display notebook Comm progress (presuming that we can hook into Comm progress in the first place).

Yep, we could do something like (not-tested)

```python
from __future__ import division
import requests

url = ...

# `stream=True` lets us stream over the response
r = requests.get(url, stream=True)

# get the total file size
total_size = int(r.headers.get('content-length', 0));

# we'll want to iterate over the file by chunks
block_size = 1024

# how much we've written locally (kernel-side)
wrote = 0

# "stream" the remote asset to ``local_file``
with open(local_file, 'wb') as f:
    for data in r.iter_content(block_size):
        # keep track of how much we've written
        f.write(data)
        wrote += len(data)

        # update the ``progress`` traitlet, which
        # we will handle on the client-side in some loading
        # notification (e.g., loading bar via tqdm?, spinny wheel, etc.)
        progress = wrote / total_size
```

> And finally, on the detached header point: I bet it would not be too much work to add an "overlay href data only" capability, since we already have headermod / header-only push and the expression in the constructor is "data" plus "overrides" (header).

Agreed that it wouldn't be difficult.

> In the notebook context, we could keep the header in a traitlet, allowing a nice Python syntax for headermod like h.xstart = 123 (triggering an observer in the client, which would then call SigPlot[.layer].headermod on the client. Even without that syntax, keeping the header in memory and the data on disk could be virtuous in terms of disk access patterns.

That seems reasonable.

**Comment by sterre** [comment] 2019-04-01 20:30
Given that we control the horizontal and the vertical in this instance, it seems like we'd be able to get a good improvement just by implementing our own serialize/deserialize to bypass `json_clean`! I still like the `ArrayBuffer` approach better overall, of course.

FWIW, if we replace the data in the "big data" fiddle with `Math.random()` instead of a ramp, the full range of data takes more like 10 sec to render (compared with ~2 sec for the ramp).

**Comment by mrecachinas** [comment] 2019-04-01 21:04
@sterre This also could be driving the slowness...

```
...
            self.array_obj = array_obj
            self.arrays.append(self.array_obj)
            self.oldArrays = self.arrays
...
```

We're incurring two syncs each time we plot (i.e., `overlay_array`).

**Comment by maihde** [comment] 2019-04-01 21:47
I agree with your results.  SigPlot has an optimization to not render
duplicate points if they occupy the same pixel (a cheater `xcmp`).  With
ramp this overlap happens more often so we are actually drawing fewer
points and lines.  Per this discussion and many others, I'm planning on
implementing an`xcmp` feature for Layer1D so that regardless of _what_ you
are plotting, the same number of points plotted are the same.  Depending on
your needs this can be good or bad so it will stay with the legacy XPLOT
behavior by default.

**Comment by maihde** [comment] 2019-04-02 00:29
@sterre One other thing to add, the Jupyter python kernel takes upwards of
two minutes or more to serialize and transfer the 20e6 points while
spinning the CPU and 100%.  This is all before anything hits the browser
and is transferred via the web socket.

So the overall ten seconds in pure JavaScript isn’t bad.

The odd thing is that Python JSON outside of Jupyter is still slow...but
not on the order of multiple minutes.

**Comment by sterre** [comment] 2019-04-02 16:48
I wouldn't be surprised if the `json_clean` function that @mrecachinas found, plus the multiple assignments, are the source of the additional time. 

`oldArrays` is used for two purposes that I see:
* To stash arrays that are overlaid before the client half of the widget has cosntructed / rendered
* To avoid overlaying the same array multiple times

`array_obj` is used to trigger the client's overlay after the client half of the widget is rendered.

This is already a little confusing because the timing aspect of it is not documented.

I can think of a couple of ideas for reducing the number of syncs as well as clarifying the intent a bit. One approach might be to just remember, in the client, what we've already overlaid (e.g., by index into `oldArrays`). We could dispense with `array_obj`, removing one sync. Then whenever the list of overlaid arrays changes, the client, not the server, decides what's new.  I _suspect_ this will help clear up behavior when multiple arrays are overlaid in one call.

However, because we're syncing the entire history of all arrays that have ever been overlaid, we're doing the most possible work we can whenever we add a new array--we'll have to re-serialize all previously-overlaid arrays! So we might be better off using our traitlet only to communicate new arrays, and devise a scheme where the client retains what it's received historically in local variables rather than traitlets. We may want a unique id (UID), like a one-up-counter, for each array that we overlay; then the client could just ack those UIDs with a quick traitlet update (which might even UIDs for all arrays currently being plotted).

All this touches somewhat on the idea of sending more generic commands, like tuples `('command', [args])` . This would unify the array/href/file transport. We'd want to give every command a UID, rather than every array/href, but the logic would otherwise be essentially the same as above.

**Comment by mrecachinas** [comment] 2019-04-22 16:54
Optimized in 1d44f0d. It uses binary serialization/deserialization for the array rather than just JSON array serialization/deserialization. It was much much faster for the 20 million point case. If it still is an issue, feel free to open this or a new issue.

**Closed by mrecachinas** 2019-04-22 16:54 UTC
Labels: enhancement, performance
